// Copyright The Fantastic Planet - By David Clabaugh
//
// kernel.zig — Local LLM inference backend (llama.cpp + Metal)
//
// Wraps llama.cpp's C API behind the same sendMessage() interface as the
// other backends (Claude, Ollama, OpenAI-compatible). Self-contained:
// links a static libllama.a with embedded Metal shaders. No Python,
// no HTTP, no external process.
//
// Platform: macOS arm64 only (this round). On other targets, init() succeeds
// but sendMessage() returns error.KernelBackendUnavailable so the binary
// still builds for cross-compile workflows.
//
// Forward path: when forAI ships its own Metal-quantized inference, the
// llama.cpp dependency gets swapped for libforai_kernel.a. Only this file
// changes — Backend union, switchBackend, alias map, and CLI all stay put.
//
// Spec: docs/superpowers/specs/2026-04-26-wintermolt-kernel-backend.md

const std = @import("std");
const builtin = @import("builtin");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;
const protocol = @import("protocol.zig");
const sse = @import("sse.zig");

/// True when this build can actually run llama.cpp inference.
pub const is_supported =
    builtin.target.os.tag == .macos and
    builtin.target.cpu.arch == .aarch64;

pub const Error = error{
    KernelBackendUnavailable,
    ModelNotFound,
    ModelLoadFailed,
    ContextInitFailed,
    TokenizeFailed,
    DecodeFailed,
    SamplerInitFailed,
    OutOfMemory,
};

// llama.cpp C ABI — auto-generated by Zig from the real headers shipped under
// prebuilt/macos/include_kernel/. Only compiled on darwin-arm64.
const c = if (is_supported) @cImport({
    @cInclude("llama.h");
}) else struct {};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

pub const KernelClient = struct {
    alloc: Allocator,
    model_path: []const u8,
    model_alias: []const u8,
    ctx_size: u32 = 4096,
    ngl: i32 = 999, // GPU layers — 999 means "all to Metal"
    max_tokens: u32 = 2048,
    temperature: f32 = 0.7,
    top_p: f32 = 0.9,
    top_k: i32 = 40,
    seed: u32 = 0xC0DE_FACE,

    loaded: bool = false,
    model_handle: if (is_supported) ?*c.llama_model else void = if (is_supported) null else {},
    ctx_handle: if (is_supported) ?*c.llama_context else void = if (is_supported) null else {},
    sampler: if (is_supported) ?*c.llama_sampler else void = if (is_supported) null else {},

    pub fn init(alloc: Allocator, model_path: []const u8, model_alias: []const u8) KernelClient {
        return .{
            .alloc = alloc,
            .model_path = model_path,
            .model_alias = model_alias,
        };
    }

    pub fn deinit(self: *KernelClient) void {
        if (!is_supported) return;
        if (self.sampler) |s| c.llama_sampler_free(s);
        if (self.ctx_handle) |cx| c.llama_free(cx);
        if (self.model_handle) |m| c.llama_model_free(m);
        self.sampler = null;
        self.ctx_handle = null;
        self.model_handle = null;
        self.loaded = false;
    }

    pub fn sendMessage(
        self: *KernelClient,
        system_prompt: []const u8,
        messages: []const protocol.Message,
        tool_defs: []const protocol.ToolDefinition,
        text_cb: ?sse.TextCallback,
    ) !protocol.Response {
        if (!is_supported) return Error.KernelBackendUnavailable;

        if (tool_defs.len > 0) {
            const stderr = std.fs.File.stderr().deprecatedWriter();
            stderr.writeAll("[kernel] tool_defs ignored — kernel backend is text-only. Use /model claude for tool work.\n") catch {};
        }

        try self.ensureLoaded();

        const prompt = try self.formatPrompt(system_prompt, messages);
        defer self.alloc.free(prompt);

        return self.generateStream(prompt, text_cb);
    }

    fn ensureLoaded(self: *KernelClient) !void {
        if (!is_supported) return Error.KernelBackendUnavailable;
        if (self.loaded) return;

        const stderr = std.fs.File.stderr().deprecatedWriter();
        stderr.print("[kernel] Loading {s} from {s}...\n", .{ self.model_alias, self.model_path }) catch {};

        c.llama_backend_init();

        // Null-terminated path for C API
        const path_z = try self.alloc.dupeZ(u8, self.model_path);
        defer self.alloc.free(path_z);

        var mparams = c.llama_model_default_params();
        mparams.n_gpu_layers = self.ngl; // offload everything to Metal

        const model = c.llama_model_load_from_file(path_z.ptr, mparams) orelse {
            stderr.print("[kernel] Failed to load model from {s}\n", .{self.model_path}) catch {};
            return Error.ModelLoadFailed;
        };
        self.model_handle = model;

        var cparams = c.llama_context_default_params();
        cparams.n_ctx = self.ctx_size;
        cparams.n_batch = self.ctx_size; // batch == ctx is fine for single-user chat
        cparams.no_perf = true;

        const ctx = c.llama_init_from_model(model, cparams) orelse {
            stderr.writeAll("[kernel] Failed to init context\n") catch {};
            return Error.ContextInitFailed;
        };
        self.ctx_handle = ctx;

        // Sampler chain: top_k → top_p → temp → dist(seed)
        var schain_params = c.llama_sampler_chain_default_params();
        schain_params.no_perf = true;
        const chain = c.llama_sampler_chain_init(schain_params) orelse {
            stderr.writeAll("[kernel] Failed to init sampler chain\n") catch {};
            return Error.SamplerInitFailed;
        };
        c.llama_sampler_chain_add(chain, c.llama_sampler_init_top_k(self.top_k));
        c.llama_sampler_chain_add(chain, c.llama_sampler_init_top_p(self.top_p, 1));
        c.llama_sampler_chain_add(chain, c.llama_sampler_init_temp(self.temperature));
        c.llama_sampler_chain_add(chain, c.llama_sampler_init_dist(self.seed));
        self.sampler = chain;

        self.loaded = true;
        stderr.print("[kernel] {s} loaded ({d} GPU layers, ctx={d})\n", .{ self.model_alias, self.ngl, self.ctx_size }) catch {};
    }

    /// Format messages into a chat-template string. We use the model's GGUF-embedded jinja
    /// template via llama_chat_apply_template for correctness across Gemma/Qwen/Llama.
    fn formatPrompt(
        self: *KernelClient,
        system_prompt: []const u8,
        messages: []const protocol.Message,
    ) ![]u8 {
        if (!is_supported) return Error.KernelBackendUnavailable;

        // Build a flat plain-text representation of each message for chat_apply_template.
        // tool_use/tool_result blocks get serialized as text since the kernel backend is text-only.
        var msg_count: usize = 0;
        if (system_prompt.len > 0) msg_count += 1;
        msg_count += messages.len;

        const chat = try self.alloc.alloc(c.llama_chat_message, msg_count);
        defer self.alloc.free(chat);

        // Track allocated content strings so we can free them
        var content_alloc: ArrayList([]u8) = .{};
        defer {
            for (content_alloc.items) |s| self.alloc.free(s);
            content_alloc.deinit(self.alloc);
        }

        var idx: usize = 0;
        if (system_prompt.len > 0) {
            const role = try self.alloc.dupeZ(u8, "system");
            try content_alloc.append(self.alloc, role);
            const content = try self.alloc.dupeZ(u8, system_prompt);
            try content_alloc.append(self.alloc, content);
            chat[idx] = .{ .role = role.ptr, .content = content.ptr };
            idx += 1;
        }
        for (messages) |msg| {
            var buf: ArrayList(u8) = .{};
            const w = buf.writer(self.alloc);
            for (msg.content.items) |block| {
                switch (block) {
                    .text => |t| try w.writeAll(t),
                    .tool_use => |tu| try w.print("[tool_use {s}({s})]", .{ tu.name, tu.input_json }),
                    .tool_result => |tr| try w.print("[tool_result: {s}]", .{tr.content}),
                    .image => try w.writeAll("[image omitted — kernel backend is text-only]"),
                }
            }
            const content_slice = try buf.toOwnedSlice(self.alloc);
            const content_z = try self.alloc.dupeZ(u8, content_slice);
            self.alloc.free(content_slice);
            try content_alloc.append(self.alloc, content_z);

            const role_z = try self.alloc.dupeZ(u8, msg.role.toString());
            try content_alloc.append(self.alloc, role_z);
            chat[idx] = .{ .role = role_z.ptr, .content = content_z.ptr };
            idx += 1;
        }

        // First call: get required size (negative if buf too small)
        const initial_buf_size: i32 = 8192;
        var out_buf = try self.alloc.alloc(u8, @intCast(initial_buf_size));
        errdefer self.alloc.free(out_buf);

        const n = c.llama_chat_apply_template(
            null, // tmpl=null → use model's GGUF-embedded template
            chat.ptr,
            chat.len,
            true, // add_ass = true → append assistant turn marker
            out_buf.ptr,
            initial_buf_size,
        );

        if (n < 0) return Error.TokenizeFailed;
        if (n > initial_buf_size) {
            out_buf = try self.alloc.realloc(out_buf, @intCast(n));
            const n2 = c.llama_chat_apply_template(null, chat.ptr, chat.len, true, out_buf.ptr, n);
            if (n2 < 0) return Error.TokenizeFailed;
            return out_buf[0..@intCast(n2)];
        }
        return out_buf[0..@intCast(n)];
    }

    fn generateStream(
        self: *KernelClient,
        prompt: []const u8,
        text_cb: ?sse.TextCallback,
    ) !protocol.Response {
        if (!is_supported) return Error.KernelBackendUnavailable;
        const ctx = self.ctx_handle orelse return Error.ContextInitFailed;
        const sampler = self.sampler orelse return Error.SamplerInitFailed;
        const model = self.model_handle orelse return Error.ModelLoadFailed;
        const vocab = c.llama_model_get_vocab(model);

        // Tokenize prompt. First call with size 0 returns required count (negative).
        const prompt_z = try self.alloc.dupeZ(u8, prompt);
        defer self.alloc.free(prompt_z);

        const n_prompt = -c.llama_tokenize(vocab, prompt_z.ptr, @intCast(prompt.len), null, 0, true, true);
        if (n_prompt <= 0) return Error.TokenizeFailed;

        const tokens = try self.alloc.alloc(c.llama_token, @intCast(n_prompt));
        defer self.alloc.free(tokens);

        const got = c.llama_tokenize(vocab, prompt_z.ptr, @intCast(prompt.len), tokens.ptr, n_prompt, true, true);
        if (got < 0) return Error.TokenizeFailed;

        // Initial decode: feed entire prompt
        var batch = c.llama_batch_get_one(tokens.ptr, n_prompt);
        if (c.llama_decode(ctx, batch) != 0) return Error.DecodeFailed;

        // Streaming generation loop
        var resp = protocol.Response.init(self.alloc);
        var accumulated: ArrayList(u8) = .{};
        defer accumulated.deinit(self.alloc);

        var generated: u32 = 0;
        while (generated < self.max_tokens) : (generated += 1) {
            var token = c.llama_sampler_sample(sampler, ctx, -1);
            if (c.llama_vocab_is_eog(vocab, token)) break;
            c.llama_sampler_accept(sampler, token);

            // token → UTF-8 piece
            var piece_buf: [256]u8 = undefined;
            const piece_n = c.llama_token_to_piece(vocab, token, &piece_buf, piece_buf.len, 0, false);
            if (piece_n < 0) break;
            const piece = piece_buf[0..@intCast(piece_n)];

            try accumulated.appendSlice(self.alloc, piece);
            if (text_cb) |cb| cb(piece);

            // Decode next single token
            batch = c.llama_batch_get_one(&token, 1);
            if (c.llama_decode(ctx, batch) != 0) break;
        }

        const text_owned = try self.alloc.dupe(u8, accumulated.items);
        try resp.content.append(self.alloc, .{ .text = text_owned });
        resp.stop_reason = if (generated >= self.max_tokens) .max_tokens else .end_turn;
        return resp;
    }
};

// ---------------------------------------------------------------------------
// Model resolution
// ---------------------------------------------------------------------------

pub const ResolvedModel = struct {
    repo: []const u8, // Hugging Face repo (e.g. "bartowski/Qwen2.5-7B-Instruct-GGUF")
    file: []const u8, // GGUF filename within the repo
};

// =============================================================================
//  ░░░  USER CONTRIBUTION POINT  ░░░
//
//  Pick the canonical GGUFs that ship as Wintermolt's defaults. Anything not
//  in this map can still be loaded by absolute path or by dropping a file
//  into ~/.wintermolt/models/<alias>.gguf — but the aliases below are what
//  `/model kernel gemma3` and friends will resolve to out-of-the-box.
//
//  Considerations:
//    - Q4_K_M is the usual quality/size sweet spot on Apple Silicon
//    - Gemma 3 4B Q4_K_M ≈ 2.5GB; Gemma 3 12B Q4_K_M ≈ 7GB
//    - Qwen 3 8B Q4_K_M ≈ 5GB; Qwen 3 0.6B ≈ 400MB (good for testing)
//    - Reputable repos: unsloth/, bartowski/, ggml-org/, lmstudio-community/
//
//  Return null for an unrecognized alias — the caller falls through to the
//  local-file lookup before giving up.
// =============================================================================
pub fn resolveAlias(alias: []const u8) ?ResolvedModel {
    // Built-in defaults (David: replace/extend with curated repos):
    if (std.mem.eql(u8, alias, "qwen3:0.6b"))
        return .{ .repo = "Qwen/Qwen2.5-0.5B-Instruct-GGUF", .file = "qwen2.5-0.5b-instruct-q4_k_m.gguf" };
    return null;
}

/// Resolve `/model kernel <alias>` to a concrete GGUF path. Lookup order:
///   1. Absolute or ~-prefixed path → use as-is
///   2. <model_dir>/<alias>.gguf
///   3. <model_dir>/<alias>/*.gguf (first match)
///   4. Alias map → print download hint, return ModelNotFound
pub fn resolveModelPath(alloc: Allocator, alias: []const u8, model_dir: []const u8) ![]const u8 {
    if (alias.len == 0) return Error.ModelNotFound;

    // 1. Absolute or home-prefixed
    if (alias[0] == '/' or alias[0] == '~') {
        return try expandHome(alloc, alias);
    }

    // 2. <model_dir>/<alias>.gguf
    {
        const direct = try std.fmt.allocPrint(alloc, "{s}/{s}.gguf", .{ model_dir, alias });
        if (std.fs.cwd().access(direct, .{})) |_| {
            return direct;
        } else |_| {
            alloc.free(direct);
        }
    }

    // 3. <model_dir>/<alias>/*.gguf
    {
        const subdir = try std.fmt.allocPrint(alloc, "{s}/{s}", .{ model_dir, alias });
        defer alloc.free(subdir);
        if (std.fs.cwd().openDir(subdir, .{ .iterate = true })) |dir_const| {
            var dir = dir_const;
            defer dir.close();
            var it = dir.iterate();
            while (try it.next()) |entry| {
                if (entry.kind == .file and std.mem.endsWith(u8, entry.name, ".gguf")) {
                    return try std.fmt.allocPrint(alloc, "{s}/{s}", .{ subdir, entry.name });
                }
            }
        } else |_| {}
    }

    // 4. Alias map → download hint
    if (resolveAlias(alias)) |resolved| {
        const stderr = std.fs.File.stderr().deprecatedWriter();
        stderr.print(
            "[kernel] Model '{s}' not found locally.\n  Download with:\n    huggingface-cli download {s} {s} --local-dir {s}/{s}\n",
            .{ alias, resolved.repo, resolved.file, model_dir, alias },
        ) catch {};
    } else {
        const stderr = std.fs.File.stderr().deprecatedWriter();
        stderr.print(
            "[kernel] Unknown model alias '{s}'. Drop a GGUF at {s}/{s}.gguf or extend resolveAlias() in src/api/kernel.zig.\n",
            .{ alias, model_dir, alias },
        ) catch {};
    }

    return Error.ModelNotFound;
}

fn expandHome(alloc: Allocator, path: []const u8) ![]const u8 {
    if (path.len == 0 or path[0] != '~') return try alloc.dupe(u8, path);
    const home = std.posix.getenv("HOME") orelse return try alloc.dupe(u8, path);
    if (path.len == 1) return try alloc.dupe(u8, home);
    if (path[1] != '/') return try alloc.dupe(u8, path);
    return try std.fmt.allocPrint(alloc, "{s}{s}", .{ home, path[1..] });
}

/// Default model directory: $WINTERMOLT_KERNEL_MODEL_DIR or ~/.wintermolt/models
pub fn defaultModelDir(alloc: Allocator) ![]const u8 {
    if (std.posix.getenv("WINTERMOLT_KERNEL_MODEL_DIR")) |dir| {
        return try alloc.dupe(u8, dir);
    }
    const home = std.posix.getenv("HOME") orelse return Error.ModelNotFound;
    return try std.fmt.allocPrint(alloc, "{s}/.wintermolt/models", .{home});
}
